/**
 * This code was generated by v0 by Vercel.
 * @see https://v0.dev/t/chNgMX8oHXP
 */
import { Label } from "@/components/ui/label"
import { Input } from "@/components/ui/input"
import { Textarea } from "@/components/ui/textarea"
import { Button } from "@/components/ui/button"

export function contact() {
  return (
    (<div className="w-full px-4 py-8 md:py-16">
      <div
        className="container flex flex-col items-center justify-center space-y-4 px-4 md:px-6">
        <div className="space-y-2 text-center">
          <h2 className="text-3xl font-bold">Contact Sales</h2>
          <p className="text-gray-500 dark:text-gray-400">
            Fill out the form below and we'll get back to you as soon as possible.
          </p>
        </div>
        <div className="w-full max-w-lg space-y-4">
          <div className="space-y-2">
            <Label htmlFor="name">Name</Label>
            <Input
              className="transition-colors duration-300 ease-in-out rounded-md focus:ring-2 ring-primary-500"
              id="name"
              placeholder="Enter your name" />
          </div>
          <div className="space-y-2">
            <Label htmlFor="email">Email</Label>
            <Input
              className="transition-colors duration-300 ease-in-out rounded-md focus:ring-2 ring-primary-500"
              id="email"
              placeholder="Enter your email"
              type="email" />
          </div>
          <div className="space-y-2">
            <Label htmlFor="subject">Subject</Label>
            <Input
              className="transition-colors duration-300 ease-in-out rounded-md focus:ring-2 ring-primary-500"
              id="subject"
              placeholder="Enter the subject" />
          </div>
          <div className="space-y-2">
            <Label htmlFor="message">Message</Label>
            <Textarea
              className="min-h-[100px] transition-colors duration-300 ease-in-out rounded-md focus:ring-2 ring-primary-500"
              id="message"
              placeholder="Enter your message" />
          </div>
          <Button
            className="w-full transition-opacity duration-300 ease-in-out opacity-100 group-hover:opacity-100">
            Submit
            <span
              className="absolute inset-0 flex items-center justify-center translate-x-2/4 opacity-0 pointer-events-none group-hover:translate-x-0 group-hover:opacity-100 transition-all duration-300 ease-in-out">
              <div className="w-4 h-4 rotate-45" />
            </span>
          </Button>
        </div>
      </div>
    </div>)
  );
}
